### ISSUE TITLE
npm run setup fails when executing venv script

### ISSUE THREAD

**Issue by ttoktassynov** [louislefevre/node-red-contrib-quantum#17]
### Steps to Reproduce Bug
After cloning the project and changing directory, run `npm run setup`

### Expected Behaviour & Actual Behaviour
Expected behavior is setup installs package dependencies and links it to the node red, creates  python virtual environment and installs Qiskit package inside that environment.

Actual behavior is this error:
```
> node-red-contrib-quantum@0.0.1 venv
> python bin/pyvenv.py || bin/pyvenv.py

  File "bin/pyvenv.py", line 9
    def execute(*args, stdout=None, stderr=None):
                            ^
SyntaxError: invalid syntax
  File "bin/pyvenv.py", line 9
    def execute(*args, stdout=None, stderr=None):
                            ^
SyntaxError: invalid syntax
```

### Additional Information
When I run `python --version` it says Python 2.7.16, so I guess it has to do with python version

### System Information

* **Node.js Version**:v12.22.1
* **Operating System**:Darwin tma.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by louislefevre** [comment]
Like you said, this is likely due to the Python version. Python 2 is no longer supported as of January 2020, so there isn't much point in updating the script to be compatible with it. Update to the latest version of Python, and test the script again to see if it fixes the issue.

**Comment by ttoktassynov** [comment]
I think because I have both versions of python on my machine and I need to explicitly call python3 to work with this version, I had the issue with your script. 

Fortunately, I have managed to a setup my python3 interpreter as default one on my machine with a help of this [article](https://dev.to/malwarebo/how-to-set-python3-as-a-default-python-version-on-mac-4jjf) and now the script worked correctly.
