### ISSUE TITLE
Parallel nodes (different qubits) writing to the shell break the code

### ISSUE THREAD

**Issue by Theo-Reignier** [louislefevre/node-red-contrib-quantum#21]
### Bug Description
Two nodes operating on different qubits cannot write to the same python shell without breaking the code.
The same thing happens with two parallel registers. No error message is returned when this happens.
@louislefevre I believe you came across this issue already.

I don't know yet if the 2 nodes must be running at the exact same time to create this bug or if 2 different node-RED paths (in our case 2 different qubits) create the same issue if their respective nodes are run at different times.

**Comment by louislefevre** [comment]
Yeah this is a bug I've been looking into lately. It's not entirely clear what is causing it to come about, and I'm not sure how Node-RED works in terms of running nodes in parallel (as in, if it executes them simultaneously or one after the other). Until this is fixed perhaps it would be easiest to write code as if this bug didn't exist, and use `shell.script` to verify that the overall script is being written correctly.

**Comment by bbaayezi** [comment]
My initial thought of a possible solution: for parallel tasks, implement a message queue of tasks/commands that a node wishes the python script to execute, order the messages using logic timestamps (e.g. ascending order of quantum register ID and qubit ID), after the python shell has executed all tasks in the message queue, call the callback function and the program can move on.
