### ISSUE TITLE
Simulator node add multiple simulation command blocks instead of one in Register Only mode circuits

### ISSUE THREAD

**Issue by ttoktassynov** [louislefevre/node-red-contrib-quantum#34]
### Bug Description
When measuring two or more qubits of one register simulation nodes fails to adequately "wait" for the last arrived qubit and adds simulation command blocks the shell for all qubits measured.

### Steps to Reproduce Bug
Just measure several qubits in register only mode circuit and output the results using simulator node. Here is one example I did:
![Screen Shot 2021-07-23 at 09 44 49](https://user-images.githubusercontent.com/25239936/126758514-b5a4f760-cd82-46ec-a674-32cbea1b7c53.png)

Here is another without measurement node:
![Screen Shot 2021-07-23 at 09 54 32](https://user-images.githubusercontent.com/25239936/126759579-96bbb8cb-d1ab-4342-adf7-5bea4f0c08f2.png)

But in qubit only mode circuits simulator node works fine:
![Screen Shot 2021-07-23 at 09 55 52](https://user-images.githubusercontent.com/25239936/126759632-10edc5c2-921d-4a66-ac50-2e00161a17c3.png)

### Expected Behaviour & Actual Behaviour
Expected behaviour is simulator node adds only one set of commands and user receives only one set of results.
Actual behaviour is that user receives as many results as there are qubits in the quantum registers.

### System Information

* **Node.js Version**: v12.22.1
* **Operating System**:Darwin tma.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by Theo-Reignier** [comment]
Thank you for noticing this, I could not test the code for registers since the shell was not working with registers at this time.
The code for qubits only was tested but not using registers.

**Comment by Theo-Reignier** [comment]
I am pretty sure this issue is linked (if it isn't the same) to issue #36.

**Comment by Theo-Reignier** [comment]
This issue still exists on the 'master' branch.

<img width="1440" alt="Screenshot 2021-07-31 at 14 36 15" src="https://user-images.githubusercontent.com/72977801/127740082-c3dcac34-6faa-48c8-bb89-9f88c70c3c3b.png">

**Comment by Theo-Reignier** [comment]
Issue fixed by PR #38
