### ISSUE TITLE
Simulator node doesn't wait for the circuit to initialize by last classical register in the flow

### ISSUE THREAD

**Issue by ttoktassynov** [louislefevre/node-red-contrib-quantum#35]
### Bug Description
When there are several classical register (more than 2) the simulator node fails to wait for the circuit to initialize and starts to add to the shell simulator related scripts. It only waits for qubits to arrive, but in the meantime there are still some classical registers still processing their input messages.

### Steps to Reproduce Bug
You can build a flow like this and run it:
![Screen Shot 2021-07-23 at 13 01 25](https://user-images.githubusercontent.com/25239936/126780428-772ff2f7-ce9c-439b-8227-95b4ac75566b.png)

### Expected Behaviour & Actual Behaviour
Expected behavior is that simulator node waits not only for all qubits messages but also waits for all classical registers to finish processing their input messages, particularly by initializing the quantum circuit.

Actual behavior is that as soon as simulator node receives input from all qubits wires it starts embedding its simulation related code to the script without checking if the circuit is initialized or not, which leads to pythons errors where quantum circuit is not defined

### System Information

* **Node.js Version**: v12.22.1
* **Operating System**:Darwin tma.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by Theo-Reignier** [comment]
Thank you for noticing this, I could not test the code for registers since the shell was not working with registers at this time.
The code for qubits only was tested but not using registers.

**Comment by Theo-Reignier** [comment]
I haven't tried it yet but quantum registers could wait for the flow variable `QuantumCircuit` to be deleted (`undefined`) before sending their outputs. Using a while loop or similar structure

**Comment by Theo-Reignier** [comment]
Anyone working on this bug yet ?
I'd be interested in solving it, I think I already know how.
