### ISSUE TITLE
Logical bug in simulator.js

### ISSUE THREAD

**Issue by bbaayezi** [louislefevre/node-red-contrib-quantum#36]
### Bug Description
There is a logical bug in `simulator.js` file:
https://github.com/louislefevre/node-red-contrib-quantum/blob/21a1393ac98cc28d84ef915ddeedb23a655b8ee7/quantum/nodes/simulator/simulator.js#L39-L49
```
if (node.qubits.length == 0) node.qreg = {}; 
else if (Object.keys(node.qreg).includes(msg.payload.registerVar))
```
should be changed to
```
if (node.qubits.length == 0) node.qreg = {}; 
if (Object.keys(node.qreg).includes(msg.payload.registerVar))
```
otherwise it won't properly count the first qubit in first quantum register.

### Additional Information
sample console log output:
```
{}
{ qr1: { total: 2, count: 1 } }
{ qr1: { total: 2, count: 1 }, qr0: { total: 2, count: 1 } }
{ qr1: { total: 2, count: 2 }, qr0: { total: 2, count: 1 } }
```
there are 4 valid inputs, 2 quantum registers with 2 qubits each, but the first qubit in the first quantum register didn't get counted.

### System Information

* **Node.js Version**: v16.5.0
* **Operating System**: WSL2 (Ubuntu 20.04)

**Comment by Theo-Reignier** [comment]
Thank you for noticing this, I could not test the code for registers since the shell was not working with registers at this time.
The code for qubits only was tested but not using registers. 

I'll look into it, thank you.

**Comment by bbaayezi** [comment]
> Thank you for noticing this, I could not test the code for registers since the shell was not working with registers at this time.
> The code for qubits only was tested but not using registers.
> 
> I'll look into it, thank you.

don't worry, I have fixed it on my local branch where I also fixed the registers issue, I will open a PR later today and apply all fixes together.
