### ISSUE TITLE
Implement global state management

### ISSUE THREAD

**Issue by bbaayezi** [louislefevre/node-red-contrib-quantum#47]
### Enhancement Description
As discussed in the previous meeting, it would be great to replace the use of flow context variables with global state variables managed by an external source file.

### Usage
It can be used to track the state of quantum registers and quantum circuit initialisation, it can also potentially be used to record the states of classical registers and change how measurement nodes work.

**Comment by Theo-Reignier** [comment]
If we manage to implement such global state management, it would be very very useful for the following aspects of the project:

- registers initialisation
- `qc` initialisation
- classical register node communication
- measurement node communication
- simulator node 'waiting' phase

**Comment by louislefevre** [comment]
Gonna take a look at this.
