### ISSUE TITLE
Single-qubit gate, multi-qubits gate, initialisation & output node templates in template folder

### ISSUE THREAD

**Issue by Theo-Reignier** [louislefevre/node-red-contrib-quantum#72]
### Enhancement Description
Node-RED Quantum nodes can be grouped into 4 categories:

- Initialisation nodes
- Single-qubit gates
- Multi-qubits gates
- Output nodes

4 nodes templates would be best in the template folder rather than a single generic one.

### Usage
If we want the open-source community to easily build on top of our work, it would be best to have already prepared templates for each category rather than letting the developer work out the system logic himself.

**Comment by louislefevre** [comment]
Perhaps we could include a template for documentation files as well.

**Comment by Theo-Reignier** [comment]
> Perhaps we could include a template for documentation files as well.

Good point, I agree. 
Even though the priority should be the template files I believe. Then we can try to implement some documentation templates.
